version: "3"

services:
    postgres:
        image: postgres:12.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: compliance_stage
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 5050:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
volumes:
    postgres:
    pgadmin: